name: Build Test

on:
   push:
     branches:
       - main
   pull_request:
     - main


jobs:
     build:
       runs-on: ubuntu-latest

       steps:
         - uses: actions/checkout@v4
         - name: setup up JDK 17
           uses: actions/setup-java@4
           with:
             java-version: '17'
             distribution: 'zulu'
             cache: gradle



         - name: Grant execute permission for gradlew
           run: chmod +x gradlew

         - name: Check dependencies
           run: ./gradlew dependencies

         - name: Build with gradle
           run: ./gradlew build


